"""Generate a ``.env.example`` template from a spec or an :class:`EnvConfig`.

Keep a checked-in example of the variables your app needs — and keep it in sync
with the code by deriving it straight from your config object instead of editing
it by hand.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Any

_HEADER = "# Generated by llmbelt — copy to .env and fill in values"


def env_template(spec: Mapping[str, str] | Iterable[Any]) -> str:
    """Render a ``.env.example`` body from ``spec``.

    ``spec`` may be a ``{NAME: help}`` mapping, or an iterable of rows that are
    either ``NAME`` strings or ``(NAME, default, help)`` tuples (``default`` and
    ``help`` optional).
    """
    rows = spec.items() if isinstance(spec, Mapping) else spec
    lines = [_HEADER, ""]
    for row in rows:
        if isinstance(row, str):
            name, default, help_text = row, "", ""
        elif isinstance(row, tuple) and isinstance(spec, Mapping):
            # came from Mapping.items(): (name, help)
            name, default, help_text = row[0], "", row[1]
        else:  # (name, default, help)
            name = row[0]
            default = row[1] if len(row) > 1 else ""
            help_text = row[2] if len(row) > 2 else ""
        if help_text:
            lines.append(f"# {help_text}")
        lines.append(f"{name}={'' if default is None else default}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def env_template_from_config(config_cls: type) -> str:
    """Build a ``.env.example`` from an :class:`EnvConfig` subclass.

    Uses the class's ``__prefix__``, annotated field names/types, and any
    defaults, marking fields without a default as required.
    """
    prefix = getattr(config_cls, "__prefix__", "")
    annotations = config_cls._annotations()  # type: ignore[attr-defined]
    _UNSET = object()
    rows = []
    for field, annotation in annotations.items():
        if field.startswith("_"):
            continue
        env_name = prefix + field.upper()
        default = getattr(config_cls, field, _UNSET)
        type_name = getattr(annotation, "__name__", str(annotation))
        if default is _UNSET:
            help_text = f"{type_name}, required"
            default_str = ""
        else:
            help_text = f"{type_name}, optional"
            default_str = "" if default in (None, [], {}) else default
        rows.append((env_name, default_str, help_text))
    return env_template(rows)
